// Code generated by "dbusutil-gen em -type Manager"; DO NOT EDIT.

package appearance

import (
	"pkg.deepin.io/lib/dbusutil"
)

func (v *Manager) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:   "Delete",
			Fn:     v.Delete,
			InArgs: []string{"ty", "name"},
		},
		{
			Name:    "GetScaleFactor",
			Fn:      v.GetScaleFactor,
			OutArgs: []string{"scaleFactor"},
		},
		{
			Name:    "GetScreenScaleFactors",
			Fn:      v.GetScreenScaleFactors,
			OutArgs: []string{"scaleFactors"},
		},
		{
			Name:    "GetWallpaperSlideShow",
			Fn:      v.GetWallpaperSlideShow,
			InArgs:  []string{"monitorName"},
			OutArgs: []string{"slideShow"},
		},
		{
			Name:    "List",
			Fn:      v.List,
			InArgs:  []string{"ty"},
			OutArgs: []string{"list"},
		},
		{
			Name: "Reset",
			Fn:   v.Reset,
		},
		{
			Name:   "Set",
			Fn:     v.Set,
			InArgs: []string{"ty", "value"},
		},
		{
			Name:   "SetMonitorBackground",
			Fn:     v.SetMonitorBackground,
			InArgs: []string{"monitorName", "imageFile"},
		},
		{
			Name:   "SetScaleFactor",
			Fn:     v.SetScaleFactor,
			InArgs: []string{"scale"},
		},
		{
			Name:   "SetScreenScaleFactors",
			Fn:     v.SetScreenScaleFactors,
			InArgs: []string{"v"},
		},
		{
			Name:   "SetWallpaperSlideShow",
			Fn:     v.SetWallpaperSlideShow,
			InArgs: []string{"monitorName", "wallpaperSlideShow"},
		},
		{
			Name:    "Show",
			Fn:      v.Show,
			InArgs:  []string{"ty", "names"},
			OutArgs: []string{"detail"},
		},
		{
			Name:    "Thumbnail",
			Fn:      v.Thumbnail,
			InArgs:  []string{"ty", "name"},
			OutArgs: []string{"file"},
		},
	}
}
