// Code generated by "dbusutil-gen em -type Manager"; DO NOT EDIT.

package airplane_mode

import (
	"github.com/linuxdeepin/go-lib/dbusutil"
)

func (v *Manager) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name: "DumpState",
			Fn:   v.DumpState,
		},
		{
			Name:   "Enable",
			Fn:     v.Enable,
			InArgs: []string{"enableAirplaneMode"},
		},
		{
			Name:   "EnableBluetooth",
			Fn:     v.EnableBluetooth,
			InArgs: []string{"enableAirplaneMode"},
		},
		{
			Name:   "EnableWifi",
			Fn:     v.EnableWifi,
			InArgs: []string{"enableAirplaneMode"},
		},
	}
}
