// Code generated by "dbusutil-gen em -type Manager,Battery"; DO NOT EDIT.

package power

import (
	"github.com/linuxdeepin/go-lib/dbusutil"
)

func (v *Battery) GetExportedMethods() dbusutil.ExportedMethods {
	return nil
}
func (v *Manager) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:    "GetBatteries",
			Fn:      v.GetBatteries,
			OutArgs: []string{"batteries"},
		},
		{
			Name:   "LockCpuFreq",
			Fn:     v.LockCpuFreq,
			InArgs: []string{"governor", "lockTime"},
		},
		{
			Name: "Refresh",
			Fn:   v.Refresh,
		},
		{
			Name: "RefreshBatteries",
			Fn:   v.RefreshBatteries,
		},
		{
			Name: "RefreshMains",
			Fn:   v.RefreshMains,
		},
		{
			Name:   "SetCpuBoost",
			Fn:     v.SetCpuBoost,
			InArgs: []string{"enabled"},
		},
		{
			Name:   "SetCpuGovernor",
			Fn:     v.SetCpuGovernor,
			InArgs: []string{"governor"},
		},
		{
			Name:   "SetMode",
			Fn:     v.SetMode,
			InArgs: []string{"mode"},
		},
	}
}
