// Code generated by "dbusutil-gen em -type Manager"; DO NOT EDIT.

package power_manager

import (
	"pkg.deepin.io/lib/dbusutil"
)

func (v *Manager) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:    "CanHibernate",
			Fn:      v.CanHibernate,
			OutArgs: []string{"can"},
		},
		{
			Name:    "CanReboot",
			Fn:      v.CanReboot,
			OutArgs: []string{"can"},
		},
		{
			Name:    "CanShutdown",
			Fn:      v.CanShutdown,
			OutArgs: []string{"can"},
		},
		{
			Name:    "CanSuspend",
			Fn:      v.CanSuspend,
			OutArgs: []string{"can"},
		},
		{
			Name:    "CanSuspendToHibernate",
			Fn:      v.CanSuspendToHibernate,
			OutArgs: []string{"can"},
		},
		{
			Name:   "SetSuspendToHibernateTime",
			Fn:     v.SetSuspendToHibernateTime,
			InArgs: []string{"timeMinute"},
		},
	}
}
