// Code generated by "dbusutil-gen -type Manager manager.go"; DO NOT EDIT.

package systeminfo

import "github.com/jouyouyun/hardware/dmi"

func (v *Manager) setPropMemorySize(value uint64) (changed bool) {
	if v.MemorySize != value {
		v.MemorySize = value
		v.emitPropChangedMemorySize(value)
		return true
	}
	return false
}

func (v *Manager) emitPropChangedMemorySize(value uint64) error {
	return v.service.EmitPropertyChanged(v, "MemorySize", value)
}

func (v *Manager) setPropMemorySizeHuman(value string) (changed bool) {
	if v.MemorySizeHuman != value {
		v.MemorySizeHuman = value
		v.emitPropChangedMemorySizeHuman(value)
		return true
	}
	return false
}

func (v *Manager) emitPropChangedMemorySizeHuman(value string) error {
	return v.service.EmitPropertyChanged(v, "MemorySizeHuman", value)
}

func (v *Manager) setPropCurrentSpeed(value uint64) (changed bool) {
	if v.CurrentSpeed != value {
		v.CurrentSpeed = value
		v.emitPropChangedCurrentSpeed(value)
		return true
	}
	return false
}

func (v *Manager) emitPropChangedCurrentSpeed(value uint64) error {
	return v.service.EmitPropertyChanged(v, "CurrentSpeed", value)
}

func (v *Manager) setPropDMIInfo(value dmi.DMI) (changed bool) {
	if v.DMIInfo != value {
		v.DMIInfo = value
		v.emitPropChangedDMIInfo(value)
		return true
	}
	return false
}

func (v *Manager) emitPropChangedDMIInfo(value dmi.DMI) error {
	return v.service.EmitPropertyChanged(v, "DMIInfo", value)
}

func (v *Manager) setPropDisplayDriver(value string) (changed bool) {
	if v.DisplayDriver != value {
		v.DisplayDriver = value
		v.emitPropChangedDisplayDriver(value)
		return true
	}
	return false
}

func (v *Manager) emitPropChangedDisplayDriver(value string) error {
	return v.service.EmitPropertyChanged(v, "DisplayDriver", value)
}

func (v *Manager) setPropVideoDriver(value string) (changed bool) {
	if v.VideoDriver != value {
		v.VideoDriver = value
		v.emitPropChangedVideoDriver(value)
		return true
	}
	return false
}

func (v *Manager) emitPropChangedVideoDriver(value string) error {
	return v.service.EmitPropertyChanged(v, "VideoDriver", value)
}
