// Code generated by "./dbusutil-gen em -type Manager"; DO NOT EDIT.

package gesture

import (
	"pkg.deepin.io/lib/dbusutil"
)

func (v *Manager) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:   "SetEdgeMoveStopDuration",
			Fn:     v.SetEdgeMoveStopDuration,
			InArgs: []string{"duration"},
		},
		{
			Name:   "SetInputIgnore",
			Fn:     v.SetInputIgnore,
			InArgs: []string{"node", "isIgnore"},
		},
		{
			Name:   "SetShortPressDuration",
			Fn:     v.SetShortPressDuration,
			InArgs: []string{"duration"},
		},
	}
}
