# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/deepin-daemon.spec

# add or remove files that should be synced
synced_files:
    - rpm/deepin-daemon.spec
    - .packit.yaml

upstream_package_name: dde-daemon
# downstream (Fedora) RPM package name
downstream_package_name: deepin-daemon

actions:
  fix-spec-file: |
    bash -c "sed -i -r \"s/Version:(\s*)\S*/Version:\1${PACKIT_PROJECT_VERSION}/\" rpm/deepin-daemon.spec"
  post-upstream-clone: |
    cp rpm/dde-daemon.spec rpm/deepin-daemon.spec
