// Code generated by "dbusutil-gen em -type Manager"; DO NOT EDIT.

package mime

import (
	"pkg.deepin.io/lib/dbusutil"
)

func (v *Manager) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:   "AddUserApp",
			Fn:     v.AddUserApp,
			InArgs: []string{"mimeTypes", "desktopId"},
		},
		{
			Name:   "DeleteApp",
			Fn:     v.DeleteApp,
			InArgs: []string{"mimeTypes", "desktopId"},
		},
		{
			Name:   "DeleteUserApp",
			Fn:     v.DeleteUserApp,
			InArgs: []string{"desktopId"},
		},
		{
			Name:    "GetDefaultApp",
			Fn:      v.GetDefaultApp,
			InArgs:  []string{"mimeType"},
			OutArgs: []string{"defaultApp"},
		},
		{
			Name:    "ListApps",
			Fn:      v.ListApps,
			InArgs:  []string{"mimeType"},
			OutArgs: []string{"apps"},
		},
		{
			Name:    "ListUserApps",
			Fn:      v.ListUserApps,
			InArgs:  []string{"mimeType"},
			OutArgs: []string{"userApps"},
		},
		{
			Name:   "SetDefaultApp",
			Fn:     v.SetDefaultApp,
			InArgs: []string{"mimes", "desktopId"},
		},
	}
}
