// Code generated by "dbusutil-gen em -type Miracast"; DO NOT EDIT.

package miracast

import (
	"pkg.deepin.io/lib/dbusutil"
)

func (v *Miracast) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:   "Connect",
			Fn:     v.Connect,
			InArgs: []string{"sink", "x", "y", "w", "h"},
		},
		{
			Name:   "Disconnect",
			Fn:     v.Disconnect,
			InArgs: []string{"sink"},
		},
		{
			Name:   "Enable",
			Fn:     v.Enable,
			InArgs: []string{"link", "enabled"},
		},
		{
			Name:    "ListLinks",
			Fn:      v.ListLinks,
			OutArgs: []string{"links"},
		},
		{
			Name:    "ListSinks",
			Fn:      v.ListSinks,
			OutArgs: []string{"sinks"},
		},
		{
			Name:   "Scanning",
			Fn:     v.Scanning,
			InArgs: []string{"link", "enabled"},
		},
		{
			Name:   "SetLinkName",
			Fn:     v.SetLinkName,
			InArgs: []string{"link", "name"},
		},
	}
}
