// Code generated by "dbusutil-gen em -type SystemInfo"; DO NOT EDIT.

package systeminfo

import (
	"github.com/linuxdeepin/go-lib/dbusutil"
)

func (v *SystemInfo) GetExportedMethods() dbusutil.ExportedMethods {
	return nil
}
