// Code generated by "dbusutil-gen em -type SystemInfo"; DO NOT EDIT.

package systeminfo

import (
	"pkg.deepin.io/lib/dbusutil"
)

func (v *SystemInfo) GetExportedMethods() dbusutil.ExportedMethods {
	return nil
}
