// Code generated by "dbusutil-gen em -type TrayManager,StatusNotifierWatcher"; DO NOT EDIT.

package trayicon

import (
	"pkg.deepin.io/lib/dbusutil"
)

func (v *StatusNotifierWatcher) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:   "RegisterStatusNotifierHost",
			Fn:     v.RegisterStatusNotifierHost,
			InArgs: []string{"serviceName"},
		},
		{
			Name:   "RegisterStatusNotifierItem",
			Fn:     v.RegisterStatusNotifierItem,
			InArgs: []string{"serviceOrPath"},
		},
	}
}
func (v *TrayManager) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:   "EnableNotification",
			Fn:     v.EnableNotification,
			InArgs: []string{"win", "enabled"},
		},
		{
			Name:    "GetName",
			Fn:      v.GetName,
			InArgs:  []string{"win"},
			OutArgs: []string{"name"},
		},
		{
			Name:    "Manage",
			Fn:      v.Manage,
			OutArgs: []string{"ok"},
		},
	}
}
