// Code generated by "dbusutil-gen -type TrayManager,StatusNotifierWatcher -import pkg.deepin.io/lib/strv traymanager.go status-notifier-watcher.go"; DO NOT EDIT.

package trayicon

import (
	"pkg.deepin.io/lib/strv"
)

func (v *StatusNotifierWatcher) setPropRegisteredStatusNotifierItems(value strv.Strv) {
	v.RegisteredStatusNotifierItems = value
	v.emitPropChangedRegisteredStatusNotifierItems(value)
}

func (v *StatusNotifierWatcher) emitPropChangedRegisteredStatusNotifierItems(value strv.Strv) error {
	return v.service.EmitPropertyChanged(v, "RegisteredStatusNotifierItems", value)
}

func (v *StatusNotifierWatcher) setPropIsStatusNotifierHostRegistered(value bool) (changed bool) {
	if v.IsStatusNotifierHostRegistered != value {
		v.IsStatusNotifierHostRegistered = value
		v.emitPropChangedIsStatusNotifierHostRegistered(value)
		return true
	}
	return false
}

func (v *StatusNotifierWatcher) emitPropChangedIsStatusNotifierHostRegistered(value bool) error {
	return v.service.EmitPropertyChanged(v, "IsStatusNotifierHostRegistered", value)
}

func (v *TrayManager) setPropTrayIcons(value []uint32) {
	v.TrayIcons = value
	v.emitPropChangedTrayIcons(value)
}

func (v *TrayManager) emitPropChangedTrayIcons(value []uint32) error {
	return v.service.EmitPropertyChanged(v, "TrayIcons", value)
}
