// SPDX-FileCopyrightText: 2022 UnionTech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by "dbusutil-gen em -type XSManager"; DO NOT EDIT.

package xsettings

import (
	"github.com/linuxdeepin/go-lib/dbusutil"
)

func (v *XSManager) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:    "GetColor",
			Fn:      v.GetColor,
			InArgs:  []string{"prop"},
			OutArgs: []string{"outArg0"},
		},
		{
			Name:    "GetInteger",
			Fn:      v.GetInteger,
			InArgs:  []string{"prop"},
			OutArgs: []string{"outArg0"},
		},
		{
			Name:    "GetScaleFactor",
			Fn:      v.GetScaleFactor,
			OutArgs: []string{"outArg0"},
		},
		{
			Name:    "GetScreenScaleFactors",
			Fn:      v.GetScreenScaleFactors,
			OutArgs: []string{"outArg0"},
		},
		{
			Name:    "GetString",
			Fn:      v.GetString,
			InArgs:  []string{"prop"},
			OutArgs: []string{"outArg0"},
		},
		{
			Name:    "ListProps",
			Fn:      v.ListProps,
			OutArgs: []string{"outArg0"},
		},
		{
			Name:   "SetColor",
			Fn:     v.SetColor,
			InArgs: []string{"prop", "v"},
		},
		{
			Name:   "SetInteger",
			Fn:     v.SetInteger,
			InArgs: []string{"prop", "v"},
		},
		{
			Name:   "SetScaleFactor",
			Fn:     v.SetScaleFactor,
			InArgs: []string{"scale"},
		},
		{
			Name:   "SetScreenScaleFactors",
			Fn:     v.SetScreenScaleFactors,
			InArgs: []string{"factors"},
		},
		{
			Name:   "SetString",
			Fn:     v.SetString,
			InArgs: []string{"prop", "v"},
		},
	}
}
