#!/bin/sh
set -e

if [ "$1" = "purge" ];then
    rm -f /var/log/deepin.log 
    rm -f /var/cache/deepin/mark-setup-network-services
fi

# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'dde-backlight-helper.service' 'dde-greeter-setter.service' 'dde-lock-service.service' 'dde-system-daemon.service' 'deepin-grub2.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
