// Code generated by "dbusutil-gen em -type Manager"; DO NOT EDIT.

package launcher

import (
	"github.com/linuxdeepin/go-lib/dbusutil"
)

func (v *Manager) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:    "GetAllItemInfos",
			Fn:      v.GetAllItemInfos,
			OutArgs: []string{"list"},
		},
		{
			Name:    "GetAllNewInstalledApps",
			Fn:      v.GetAllNewInstalledApps,
			OutArgs: []string{"apps"},
		},
		{
			Name:    "GetDisableScaling",
			Fn:      v.GetDisableScaling,
			InArgs:  []string{"id"},
			OutArgs: []string{"value"},
		},
		{
			Name:    "GetItemInfo",
			Fn:      v.GetItemInfo,
			InArgs:  []string{"id"},
			OutArgs: []string{"itemInfo"},
		},
		{
			Name:    "GetUseProxy",
			Fn:      v.GetUseProxy,
			InArgs:  []string{"id"},
			OutArgs: []string{"value"},
		},
		{
			Name:    "IsItemOnDesktop",
			Fn:      v.IsItemOnDesktop,
			InArgs:  []string{"id"},
			OutArgs: []string{"result"},
		},
		{
			Name:   "MarkLaunched",
			Fn:     v.MarkLaunched,
			InArgs: []string{"id"},
		},
		{
			Name:    "RequestRemoveFromDesktop",
			Fn:      v.RequestRemoveFromDesktop,
			InArgs:  []string{"id"},
			OutArgs: []string{"ok"},
		},
		{
			Name:    "RequestSendToDesktop",
			Fn:      v.RequestSendToDesktop,
			InArgs:  []string{"id"},
			OutArgs: []string{"ok"},
		},
		{
			Name:   "RequestUninstall",
			Fn:     v.RequestUninstall,
			InArgs: []string{"id", "purge"},
		},
		{
			Name:   "Search",
			Fn:     v.Search,
			InArgs: []string{"key"},
		},
		{
			Name:   "SetDisableScaling",
			Fn:     v.SetDisableScaling,
			InArgs: []string{"id", "value"},
		},
		{
			Name:   "SetUseProxy",
			Fn:     v.SetUseProxy,
			InArgs: []string{"id", "value"},
		},
	}
}
