// Code generated by "dbusutil-gen em -type Manager"; DO NOT EDIT.

package logined

import (
	"pkg.deepin.io/lib/dbusutil"
)

func (v *Manager) GetExportedMethods() dbusutil.ExportedMethods {
	return nil
}
