// Code generated by "dbusutil-gen em -type Manager"; DO NOT EDIT.

package screenedge

import (
	"github.com/linuxdeepin/go-lib/dbusutil"
)

func (v *Manager) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:    "BottomLeftAction",
			Fn:      v.BottomLeftAction,
			OutArgs: []string{"value"},
		},
		{
			Name:    "BottomRightAction",
			Fn:      v.BottomRightAction,
			OutArgs: []string{"value"},
		},
		{
			Name:   "EnableZoneDetected",
			Fn:     v.EnableZoneDetected,
			InArgs: []string{"enabled"},
		},
		{
			Name:   "SetBottomLeft",
			Fn:     v.SetBottomLeft,
			InArgs: []string{"value"},
		},
		{
			Name:   "SetBottomRight",
			Fn:     v.SetBottomRight,
			InArgs: []string{"value"},
		},
		{
			Name:   "SetTopLeft",
			Fn:     v.SetTopLeft,
			InArgs: []string{"value"},
		},
		{
			Name:   "SetTopRight",
			Fn:     v.SetTopRight,
			InArgs: []string{"value"},
		},
		{
			Name:    "TopLeftAction",
			Fn:      v.TopLeftAction,
			OutArgs: []string{"value"},
		},
		{
			Name:    "TopRightAction",
			Fn:      v.TopRightAction,
			OutArgs: []string{"value"},
		},
	}
}
