// Code generated by "dbusutil-gen em -type Scheduler"; DO NOT EDIT.

package calendar

import (
	"pkg.deepin.io/lib/dbusutil"
)

func (v *Scheduler) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:    "CreateJob",
			Fn:      v.CreateJob,
			InArgs:  []string{"jobJSON"},
			OutArgs: []string{"id"},
		},
		{
			Name:    "CreateType",
			Fn:      v.CreateType,
			InArgs:  []string{"typeJSON"},
			OutArgs: []string{"id"},
		},
		{
			Name:   "DebugRemindJob",
			Fn:     v.DebugRemindJob,
			InArgs: []string{"id"},
		},
		{
			Name:   "DeleteJob",
			Fn:     v.DeleteJob,
			InArgs: []string{"id"},
		},
		{
			Name:   "DeleteType",
			Fn:     v.DeleteType,
			InArgs: []string{"id"},
		},
		{
			Name:    "GetJob",
			Fn:      v.GetJob,
			InArgs:  []string{"id"},
			OutArgs: []string{"jobJSON"},
		},
		{
			Name:    "GetJobs",
			Fn:      v.GetJobs,
			InArgs:  []string{"startYear", "startMonth", "startDay", "endYear", "endMonth", "endDay"},
			OutArgs: []string{"jobsJSON"},
		},
		{
			Name:    "GetJobsWithLimit",
			Fn:      v.GetJobsWithLimit,
			InArgs:  []string{"startYear", "startMonth", "startDay", "endYear", "endMonth", "endDay", "maxNum"},
			OutArgs: []string{"jobsJSON"},
		},
		{
			Name:    "GetJobsWithRule",
			Fn:      v.GetJobsWithRule,
			InArgs:  []string{"startYear", "startMonth", "startDay", "endYear", "endMonth", "endDay", "rule"},
			OutArgs: []string{"jobsJSON"},
		},
		{
			Name:    "GetType",
			Fn:      v.GetType,
			InArgs:  []string{"id"},
			OutArgs: []string{"typeJSON"},
		},
		{
			Name:    "GetTypes",
			Fn:      v.GetTypes,
			OutArgs: []string{"typesJSON"},
		},
		{
			Name:    "QueryJobs",
			Fn:      v.QueryJobs,
			InArgs:  []string{"params"},
			OutArgs: []string{"jobsJSON"},
		},
		{
			Name:    "QueryJobsWithLimit",
			Fn:      v.QueryJobsWithLimit,
			InArgs:  []string{"params", "maxNum"},
			OutArgs: []string{"jobsJSON"},
		},
		{
			Name:    "QueryJobsWithRule",
			Fn:      v.QueryJobsWithRule,
			InArgs:  []string{"params", "rule"},
			OutArgs: []string{"jobsJSON"},
		},
		{
			Name:   "UpdateJob",
			Fn:     v.UpdateJob,
			InArgs: []string{"jobJSON"},
		},
		{
			Name:   "UpdateType",
			Fn:     v.UpdateType,
			InArgs: []string{"typeJSON"},
		},
	}
}
