// Code generated by "dbusutil-gen em -type Manager"; DO NOT EDIT.

package keyevent1

import (
	"github.com/linuxdeepin/go-lib/dbusutil"
)

func (v *Manager) GetExportedMethods() dbusutil.ExportedMethods {
	return nil
}
