// Code generated by "dbusutil-gen em -type Manager"; DO NOT EDIT.

package x_event_monitor

import (
	"github.com/linuxdeepin/go-lib/dbusutil"
)

func (v *Manager) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name: "BeginTouch",
			Fn:   v.BeginTouch,
		},
		{
			Name:    "DebugGetPidAreasMap",
			Fn:      v.DebugGetPidAreasMap,
			OutArgs: []string{"pidAreasMapJSON"},
		},
		{
			Name:    "RegisterArea",
			Fn:      v.RegisterArea,
			InArgs:  []string{"x1", "y1", "x2", "y2", "flag"},
			OutArgs: []string{"id"},
		},
		{
			Name:    "RegisterAreas",
			Fn:      v.RegisterAreas,
			InArgs:  []string{"areas", "flag"},
			OutArgs: []string{"id"},
		},
		{
			Name:    "RegisterFullScreen",
			Fn:      v.RegisterFullScreen,
			OutArgs: []string{"id"},
		},
		{
			Name: "RegisterFullScreenMotionFlag",
			Fn:   v.RegisterFullScreenMotionFlag,
		},
		{
			Name:    "UnregisterArea",
			Fn:      v.UnregisterArea,
			InArgs:  []string{"id"},
			OutArgs: []string{"ok"},
		},
		{
			Name: "UnregisterFullScreenMotionFlag",
			Fn:   v.UnregisterFullScreenMotionFlag,
		},
	}
}
