// Code generated by "dbusutil-gen em -type Manager"; DO NOT EDIT.

package timedate

import (
	"github.com/linuxdeepin/go-lib/dbusutil"
)

func (v *Manager) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:   "AddUserTimezone",
			Fn:     v.AddUserTimezone,
			InArgs: []string{"zone"},
		},
		{
			Name:   "DeleteUserTimezone",
			Fn:     v.DeleteUserTimezone,
			InArgs: []string{"zone"},
		},
		{
			Name:    "GetSampleNTPServers",
			Fn:      v.GetSampleNTPServers,
			OutArgs: []string{"servers"},
		},
		{
			Name:    "GetZoneInfo",
			Fn:      v.GetZoneInfo,
			InArgs:  []string{"zone"},
			OutArgs: []string{"zoneInfo"},
		},
		{
			Name:    "GetZoneList",
			Fn:      v.GetZoneList,
			OutArgs: []string{"zoneList"},
		},
		{
			Name: "Reset",
			Fn:   v.Reset,
		},
		{
			Name:   "SetDate",
			Fn:     v.SetDate,
			InArgs: []string{"year", "month", "day", "hour", "min", "sec", "nsec"},
		},
		{
			Name:   "SetLocalRTC",
			Fn:     v.SetLocalRTC,
			InArgs: []string{"localRTC", "fixSystem"},
		},
		{
			Name:   "SetNTP",
			Fn:     v.SetNTP,
			InArgs: []string{"useNTP"},
		},
		{
			Name:   "SetNTPServer",
			Fn:     v.SetNTPServer,
			InArgs: []string{"server"},
		},
		{
			Name:   "SetTime",
			Fn:     v.SetTime,
			InArgs: []string{"usec", "relative"},
		},
		{
			Name:   "SetTimezone",
			Fn:     v.SetTimezone,
			InArgs: []string{"zone"},
		},
	}
}
