// Code generated by "dbusutil-gen -type Manager manager.go"; DO NOT EDIT.

package timedate

func (v *ManagerFormat) setPropCurrencySymbol(value string) (changed bool) {
	if v.CurrencySymbol != value {
		v.CurrencySymbol = value
		v.emitPropChangedCurrencySymbol(value)
		return true
	}
	return false
}

func (v *ManagerFormat) emitPropChangedCurrencySymbol(value string) error {
	return v.service.EmitPropertyChanged(v, "CurrencySymbol", value)
}

func (v *ManagerFormat) setPropPositiveCurrencyFormat(value string) (changed bool) {
	if v.PositiveCurrencyFormat != value {
		v.PositiveCurrencyFormat = value
		v.emitPropChangedPositiveCurrencyFormat(value)
		return true
	}
	return false
}

func (v *ManagerFormat) emitPropChangedPositiveCurrencyFormat(value string) error {
	return v.service.EmitPropertyChanged(v, "PositiveCurrencyFormat", value)
}

func (v *ManagerFormat) setPropNegativeCurrencyFormat(value string) (changed bool) {
	if v.NegativeCurrencyFormat != value {
		v.NegativeCurrencyFormat = value
		v.emitPropChangedNegativeCurrencyFormat(value)
		return true
	}
	return false
}

func (v *ManagerFormat) emitPropChangedNegativeCurrencyFormat(value string) error {
	return v.service.EmitPropertyChanged(v, "NegativeCurrencyFormat", value)
}

func (v *ManagerFormat) setPropDecimalSymbol(value string) (changed bool) {
	if v.DecimalSymbol != value {
		v.DecimalSymbol = value
		v.emitPropChangedDecimalSymbol(value)
		return true
	}
	return false
}

func (v *ManagerFormat) emitPropChangedDecimalSymbol(value string) error {
	return v.service.EmitPropertyChanged(v, "DecimalSymbol", value)
}

func (v *ManagerFormat) setPropDigitGroupingSymbol(value string) (changed bool) {
	if v.DigitGroupingSymbol != value {
		v.DigitGroupingSymbol = value
		v.emitPropChangedDigitGroupingSymbol(value)
		return true
	}
	return false
}

func (v *ManagerFormat) emitPropChangedDigitGroupingSymbol(value string) error {
	return v.service.EmitPropertyChanged(v, "DigitGroupingSymbol", value)
}

func (v *ManagerFormat) setPropDigitGrouping(value string) (changed bool) {
	if v.DigitGrouping != value {
		v.DigitGrouping = value
		v.emitPropChangedDigitGrouping(value)
		return true
	}
	return false
}

func (v *ManagerFormat) emitPropChangedDigitGrouping(value string) error {
	return v.service.EmitPropertyChanged(v, "DigitGrouping", value)
}
