// Code generated by "dbusutil-gen em -type InputDevices"; DO NOT EDIT.

package inputdevices

import (
	"github.com/linuxdeepin/go-lib/dbusutil"
)

func (v *InputDevices) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:   "SetWakeupDevices",
			Fn:     v.SetWakeupDevices,
			InArgs: []string{"path", "value"},
		},
	}
}