// Code generated by "dbusutil-gen em -type InputDevices"; DO NOT EDIT.

package inputdevices

import (
	"pkg.deepin.io/lib/dbusutil"
)

func (v *InputDevices) GetExportedMethods() dbusutil.ExportedMethods {
	return nil
}
