// Code generated by "dbusutil-gen -type InputDevices inputdevices.go"; DO NOT EDIT.

package inputdevices

import (
	"github.com/godbus/dbus"
)

func (v *InputDevices) setPropTouchscreens(value []dbus.ObjectPath) (changed bool) {
	if !touchscreenSliceEqual(v.Touchscreens, value) {
		v.Touchscreens = value
		v.emitPropChangedTouchscreens(value)
		return true
	}
	return false
}

func (v *InputDevices) emitPropChangedTouchscreens(value []dbus.ObjectPath) error {
	return v.service.EmitPropertyChanged(v, "Touchscreens", value)
}
