// Code generated by "dbusutil-gen -type EventLog event_collector.go"; DO NOT EDIT.

package eventlog

func (v *EventLog) setPropEnabled(value bool) (changed bool) {
	if v.Enabled != value {
		v.Enabled = value
		v.emitPropChangedEnabled(value)
		return true
	}
	return false
}

func (v *EventLog) emitPropChangedEnabled(value bool) error {
	return v.service.EmitPropertyChanged(v, "Enabled", value)
}
