// Code generated by "dbusutil-gen em -type EventLog"; DO NOT EDIT.

package eventlog

import (
	"github.com/linuxdeepin/go-lib/dbusutil"
)

func (v *EventLog) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:   "Enable",
			Fn:     v.Enable,
			InArgs: []string{"enable"},
		},
		{
			Name:   "ReportLog",
			Fn:     v.ReportLog,
			InArgs: []string{"log"},
		},
	}
}
