// Code generated by "dbusutil-gen em -type Lastore"; DO NOT EDIT.

package lastore

import (
	"pkg.deepin.io/lib/dbusutil"
)

func (v *Lastore) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:    "IsDiskSpaceSufficient",
			Fn:      v.IsDiskSpaceSufficient,
			OutArgs: []string{"result"},
		},
	}
}
