// Code generated by "dbusutil-gen em -type Display"; DO NOT EDIT.

package display

import (
	"github.com/linuxdeepin/go-lib/dbusutil"
)

func (v *Display) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:    "GetConfig",
			Fn:      v.GetConfig,
			OutArgs: []string{"cfgStr"},
		},
		{
			Name:   "SetConfig",
			Fn:     v.SetConfig,
			InArgs: []string{"cfgStr"},
		},
	}
}
