// Code generated by "dbusutil-gen em -type Manager"; DO NOT EDIT.

package timedated

import (
	"github.com/linuxdeepin/go-lib/dbusutil"
)

func (v *Manager) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:   "SetLocalRTC",
			Fn:     v.SetLocalRTC,
			InArgs: []string{"enabled", "fixSystem", "message"},
		},
		{
			Name:   "SetNTP",
			Fn:     v.SetNTP,
			InArgs: []string{"enabled", "message"},
		},
		{
			Name:   "SetNTPServer",
			Fn:     v.SetNTPServer,
			InArgs: []string{"server", "message"},
		},
		{
			Name:   "SetTime",
			Fn:     v.SetTime,
			InArgs: []string{"usec", "relative", "message"},
		},
		{
			Name:   "SetTimezone",
			Fn:     v.SetTimezone,
			InArgs: []string{"timezone", "message"},
		},
	}
}
