// Code generated by "dbusutil-gen -type SysBluetooth bluetooth.go"; DO NOT EDIT.

package bluetooth

func (v *SysBluetooth) setPropState(value uint32) (changed bool) {
	if v.State != value {
		v.State = value
		v.emitPropChangedState(value)
		return true
	}
	return false
}

func (v *SysBluetooth) emitPropChangedState(value uint32) error {
	return v.service.EmitPropertyChanged(v, "State", value)
}

func (v *SysBluetooth) setPropCanSendFile(value bool) (changed bool) {
	if v.CanSendFile != value {
		v.CanSendFile = value
		v.emitPropChangedCanSendFile(value)
		return true
	}
	return false
}

func (v *SysBluetooth) emitPropChangedCanSendFile(value bool) error {
	return v.service.EmitPropertyChanged(v, "CanSendFile", value)
}
