// Code generated by "dbusutil-gen em -type IPWatchD"; DO NOT EDIT.

package ipwatchd

import "github.com/linuxdeepin/go-lib/dbusutil"

func (v *IPWatchD) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:    "RequestIPConflictCheck",
			Fn:      v.RequestIPConflictCheck,
			InArgs:  []string{"ip", "ifc"},
			OutArgs: []string{"mac"},
		},
	}
}
