// Code generated by "dbusutil-gen em -type Network"; DO NOT EDIT.

package network1

import (
	"github.com/linuxdeepin/go-lib/dbusutil"
)

func (v *Network) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:    "EnableDevice",
			Fn:      v.EnableDevice,
			InArgs:  []string{"pathOrIface", "enabled"},
			OutArgs: []string{"cpath"},
		},
		{
			Name:    "IsDeviceEnabled",
			Fn:      v.IsDeviceEnabled,
			InArgs:  []string{"pathOrIface"},
			OutArgs: []string{"enabled"},
		},
		{
			Name:   "Ping",
			Fn:     v.Ping,
			InArgs: []string{"host"},
		},
		{
			Name:    "ToggleWirelessEnabled",
			Fn:      v.ToggleWirelessEnabled,
			OutArgs: []string{"enabled"},
		},
	}
}
