// Code generated by "dbusutil-gen em -type Manager"; DO NOT EDIT.

package uadp

import (
	"github.com/linuxdeepin/go-lib/dbusutil"
)

func (v *Manager) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:    "Available",
			Fn:      v.Available,
			OutArgs: []string{"outArg0"},
		},
		{
			Name:   "Delete",
			Fn:     v.Delete,
			InArgs: []string{"name"},
		},
		{
			Name:    "Get",
			Fn:      v.Get,
			InArgs:  []string{"name"},
			OutArgs: []string{"outArg0"},
		},
		{
			Name:    "ListName",
			Fn:      v.ListName,
			OutArgs: []string{"outArg0"},
		},
		{
			Name: "Release",
			Fn:   v.Release,
		},
		{
			Name:   "Set",
			Fn:     v.Set,
			InArgs: []string{"name", "data"},
		},
	}
}
