// Code generated by "dbusutil-gen em -type Manager"; DO NOT EDIT.

package sessionwatcher

import (
	"pkg.deepin.io/lib/dbusutil"
)

func (v *Manager) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:    "GetSessions",
			Fn:      v.GetSessions,
			OutArgs: []string{"sessions"},
		},
		{
			Name:    "IsX11SessionActive",
			Fn:      v.IsX11SessionActive,
			OutArgs: []string{"active"},
		},
	}
}
