// Code generated by "dbusutil-gen em -type Uadp"; DO NOT EDIT.

package uadp

import (
	"github.com/linuxdeepin/go-lib/dbusutil"
)

func (v *Uadp) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:    "GetDataKey",
			Fn:      v.GetDataKey,
			InArgs:  []string{"exePath", "keyName", "keyringKey"},
			OutArgs: []string{"dataKey"},
		},
		{
			Name:   "SetDataKey",
			Fn:     v.SetDataKey,
			InArgs: []string{"exePath", "keyName", "dataKey", "keyringKey"},
		},
	}
}
