// Code generated by "dbusutil-gen em -type Manager"; DO NOT EDIT.

package uadp

import (
	"pkg.deepin.io/lib/dbusutil"
)

func (v *Manager) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:    "DecryptData",
			Fn:      v.DecryptData,
			OutArgs: []string{"data"},
		},
		{
			Name:   "EncryptData",
			Fn:     v.EncryptData,
			InArgs: []string{"data"},
		},
	}
}
