// Code generated by "dbusutil-gen em -type UadpAgent"; DO NOT EDIT.

package uadpagent

import (
	"github.com/linuxdeepin/go-lib/dbusutil"
)

func (v *UadpAgent) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:    "GetDataKey",
			Fn:      v.GetDataKey,
			InArgs:  []string{"keyName"},
			OutArgs: []string{"dataKey"},
		},
		{
			Name:   "SetDataKey",
			Fn:     v.SetDataKey,
			InArgs: []string{"keyName", "dataKey"},
		},
	}
}
